[[redirects]]
  from = "/beta/*"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "*"
  to = "https://silver-kashata-7e0a85.netlify.app/:splat"
  status = 200
  force = false
